/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docs: [
    {
      type: 'html',
      value: "<span class='sidebar-title'>ARTICLES</span>",
      defaultStyle: true,
    },
    {
      type: 'doc',
      id: 'working-with-kpi-trends',
      label: 'Working with KPI Trends',
      className: 'sidebar-overview',
    }
  ],
   
};

module.exports = sidebars;
